spring:
  application:
    name: hw-app

  datasource:
    url: jdbc:postgresql://localhost:5433/hw_db
    username: admin
    password: wasd123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  server:
    port: 8080

  springdoc:
    api-docs:
      path: /v3/api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    packages-to-scan: ru.hw.PetrushinNickolay.controller
    paths-to-match: /api/**

  logging:
    level:
      ru.hw.PetrushinNickolay: DEBUG
      org.springframework.web: INFO
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
    file:
      name: application.log


app:
  document:
    batch-size: 5
submit:
  worker:
    delay: 10
approve:
  worker:
    delay: 15
